### ISSUE TITLE
DynamoDB Local com Docker localstack

### ISSUE THREAD

**Issue by ddamacena** [diegolirio/kotlin-spring-boot#2]
### Docker

```yml
version: "3"

services:
  localstack:
    image: localstack/localstack:0.12.16
    ports:
      - "4566-4599:4566-4599"
      - "8085:8080"
    environment:
      - SERVICES=dynamodb,s3
    volumes:
      - './.localstack:/tmp/localstack'
```
