### ISSUE TITLE
Configurando Vault Aplicacao Spring Boot

### ISSUE THREAD

**Issue by ddamacena** [diegolirio/kotlin-spring-boot#3]
### Docker-Compose

---

### Bootstrap.yml

```yml
spring:
  cloud:
    config:
      enabled: false
    vault:
      host: 127.0.0.1
      kv:
        enabled: true
      port: 8200
      scheme: http
      token: 00000000-0000-0000-0000-000000000000
```

### Application.yml e a convenção de Nomes

```yml
spring:
   application:
       name: my-app
```
